name: GitHub Actions for Assessment of Trivago Co.
run-name: ${{ github.actor }} is testing out GitHub Actions üöÄ
on: [push]
env:
  PROJECT: manouchehrsolamani
  IMAGE1: appv1
  IMAGE2: appv2
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      # - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      # - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      # - name: Check out repository code
      #   uses: actions/checkout@v3
      # - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      # - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      # - name: List files in the repository
      #   run: |
      #     ls ${{ github.workspace }}
      # - run: echo "üçè This job's status is ${{ job.status }}."

      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: appv1
          push: true
          tags: ${{ env.PROJECT }}/${{ env.IMAGE1 }}:${{ github.sha }}
          # tags: ${{ env.PROJECT }}/${{ env.IMAGE1 }}:${{ github.ref }}:${{ github.sha }}
      
      - name: Build container image
        uses: docker/build-push-action@v4
        with:
          context: appv2
          push: true
          tags: ${{ env.PROJECT }}/${{ env.IMAGE2 }}:${{ github.sha }}
          # tags: ${{ env.PROJECT }}/${{ env.IMAGE2 }}:${{ github.ref }}:${{ github.sha }}

      - name: Scan Dockerfile using Checkov
        continue-on-error: true
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: appv1
          framework: dockerfile
          quiet: true 
          container_user: 1000
      
      